version: "2"
services:
    homebridge:
        container_name: homebridge
        image: raigen/rpi-homebridge-fhem
        #volumes:
            #- ./config.json:/root/.homebridge/config.json
        ports:
            - "51826:51826"
        network_mode: "host"
